Add uninstall for installed elixirs

diff --git a/kiex b/kiex
--- a/kiex
+++ b/kiex
@@ -623,6 +623,70 @@ function install_elixir() {
   esac
 }
 
+function uninstall_elixir() {
+  typeset version delete_version current_elixir default_elixir iexpath x1
+  declare -A ealiases=()
+  typeset alias_file alias_name target_file target_name target_alias_list a
+
+  version="$1"
+  delete_version=$(find_elixir_ver "$version")
+
+  if [[ -z "$delete_version" ]]; then
+    echo "Elixir version '$version' not found."
+    exit 1
+  fi
+
+  if [[ -e "$elixirs_path"/.default ]]; then
+    default_elixir="elixir-$(source $elixirs_path/.default ; echo $ELIXIR_VERSION)"
+  fi
+
+  iexpath=$(which iex 2> /dev/null)
+  if [[ -n "${iexpath}" ]]; then
+    x1=${iexpath/$elixirs_path\/}
+    current_elixir=${x1/\/bin\/iex}
+  fi
+
+  if [[ "$delete_version" == "$current_elixir" ]]; then
+    echo "'$version' is the current version of Elixir."
+    echo "Please set kiex to use another version of Elixir and try again."
+    exit 1
+  fi
+
+  if [[ "$delete_version" == "$default_elixir" ]]; then
+    reset_elixir > /dev/null
+  fi
+
+  # remove aliases
+  pushd "$elixirs_path" > /dev/null
+  target_alias_list=""
+  for alias_file in $(find . -maxdepth 1 -mindepth 1 -type l -name ".elixir-*")
+  do
+    alias_name="${alias_file//.\/.elixir-}"
+    target_file="$(readlink $alias_file)"
+    target_name="$(basename $target_file .env)"
+
+    target_alias_list="${ealiases[$target_name]}"
+    if [[ -z "$target_alias_list" ]]; then
+      target_alias_list="$alias_name"
+    else
+      target_alias_list="$target_alias_list $alias_name"
+    fi
+    ealiases[$target_name]=$target_alias_list
+  done
+  popd > /dev/null
+
+  target_alias_list=${ealiases[$delete_version]}
+  for a in $target_alias_list; do
+    remove_alias "$a"
+  done
+
+  # remove the actual files
+  rm -f "$KIEX_HOME/elixirs/.$delete_version.env."*sh*
+  rm -Rf "$KIEX_HOME/elixirs/$delete_version"
+  rm -f "$KIEX_HOME/elixirs/$delete_version.env"*
+  rm -Rf "$KIEX_HOME/mix/archives/$delete_version"
+}
+
 function create_env_file() {
   new_ver="$1"
   new_file="${elixirs_path}/elixir-${new_ver}.env"
@@ -964,6 +1028,10 @@ case $action in
       exit
     fi
     install_elixir "$1"
+    ;;
+  uninstall)
+    [[ -z "$1" ]] && usage && exit 1
+    uninstall_elixir "$1"
     ;;
   use)
     [[ -z "$1" ]] && usage && exit 1
