Added FreeBSD support

diff --git a/kiex b/kiex
--- a/kiex
+++ b/kiex
@@ -38,6 +38,8 @@ if [ "$SYSTEM" = "Linux" ] ; then
   else
     echo "Unknown Linux distribution"
   fi
+elif [ "$SYSTEM" = "FreeBSD" ] ; then
+  DISTRO=FreeBSD
 elif [ "$SYSTEM" = "Darwin" ] ; then
   #DISTRO=$(uname -r)
   DISTRO=OSX
@@ -90,7 +92,7 @@ function readlink_f() {
 function check_erlang_release() {
   if [ "$SYSTEM" = "Linux" ] ; then
     erlang_release_file="$(dirname $(readlink -f $(which erl 2> /dev/null)))/../releases/RELEASES"
-  elif [ "$SYSTEM" = "Darwin" ] ; then
+  elif [ "$SYSTEM" = "Darwin" -o "$SYSTEM" = "FreeBSD" ] ; then
     erlang_release_file="$(dirname $(readlink_f $(which erl 2> /dev/null)))/../releases/RELEASES"
   else
       echo "Unknown system $SYSTEM"
@@ -143,9 +145,11 @@ function check_erlang_release() {
   fi
 }
 
-function erlang_bin_found() {
-  if [ -z "$(which erl 2> /dev/null)" ] ; then
-    echo "Erlang binary not found" 1>&2
+function bin_found() {
+  if [ -z "$1" ] ; then
+    false
+  elif [ -z "$(which $1 2> /dev/null)" ] ; then
+    echo "ERROR: $1 not found in \$PATH" 1>&2
     false
   else
     true
@@ -156,18 +160,38 @@ function exit_on_unmet_prereqs() {
   deps_check
   if [ ! "$?" = 0 ]
   then
-    echo "Elixir requires Erlang ${erlang_min_release_full} or later"
-    echo "Install via:"
-    echo "   * Download - https://www.erlang-solutions.com/downloads/download-erlang-otp"
-    echo "                http://www.erlang.org/download.html"
-    echo "   * Kerl - https://github.com/spawngrid/kerl"
-    echo "   * Package manager, OS X brew install erlang, Ubuntu/Debian/CentOS see erlang-solutions, Arch see AUR"
     exit 1
   fi
 }
 
+function erlang_req_info() {
+  echo "Elixir requires Erlang ${erlang_min_release_full} or later"
+  echo "Install via:"
+  echo "   * Download - https://www.erlang-solutions.com/downloads/download-erlang-otp"
+  echo "                http://www.erlang.org/download.html"
+  echo "   * Kerl - https://github.com/spawngrid/kerl"
+  echo "   * Package manager, OS X brew install erlang, Ubuntu/Debian/CentOS see erlang-solutions, Arch see AUR,"
+  echo "   *                  FreeBSD pkg install erlang"
+}
+
 function deps_check() {
-  erlang_bin_found && check_erlang_release
+  error=0
+
+  bin=erl
+  ( bin_found $bin && check_erlang_release ) || error=1
+  [[ $error = 1 ]] && erlang_req_info
+
+  bin=git
+  bin_found $bin || error=1
+  [[ $error = 1 ]] && echo "    Install $bin and try again"
+
+  if [ "$SYSTEM" = "FreeBSD" ] ; then
+    bin=gmake
+    bin_found $bin || error=1
+    [[ $error = 1 ]] && echo "    Install $bin and try again"
+  fi
+
+  if [ "$error" = 1 ] ; then false ; else true ; fi
 }
 
 function create_kiex_env_script() {
@@ -291,12 +315,20 @@ function install_elixir() {
   git fetch -t
   git checkout -f "v${version}"
   git pull origin "v${version}"
-  make clean compile
+  if [ "$SYSTEM" = "FreeBSD" ] ; then
+    MAKE=gmake
+  else
+    MAKE=make
+  fi
+  $MAKE clean compile
   mkdir -p "$install_path"
-  make "PREFIX=$install_path" install
+  $MAKE "PREFIX=$install_path" install
   echo "Installed Elixir version $version"
   create_env_file "$version"
-  echo "Load the elixir environment file with: "
+
+  echo "Load with:"
+  echo "           kiex use elixir-${version} "
+  echo "or load the elixir environment file with: "
   printf "%b" "   "
   printf "%b" "source ${elixirs_source_path}/elixir-${version}.env\n"
 }
